#!/bin/bash

factorize_number() {
    n=$1
    for ((i = 2; i < n; i++)); do
        if ((n % i == 0)); then
            echo "$n=$i*$(($n / $i))"
            return
        fi
    done
}

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

filename=$1

while IFS= read -r line; do
    number=$(echo "$line" | tr -d '\n')
    factorize_number "$number"
done < "$filename"

